-- 1. Switch to the Pluggable Database
ALTER SESSION SET CONTAINER = FREEPDB1;

-- 2. Create the speedrun user
-- We use a block to ignore error if user already exists
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER speedrun IDENTIFIED BY speedrun';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, DBA TO speedrun';
    EXECUTE IMMEDIATE 'ALTER USER speedrun QUOTA UNLIMITED ON USERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN -- Ignore "user already exists" or similar
            NULL;
        END IF;
END;
/

-- 3. Set the current schema to speedrun for the rest of the script
-- This ensures all tables and procedures are created in the speedrun schema
ALTER SESSION SET CURRENT_SCHEMA = speedrun;

-- 4. Create Tables (Drop first if they exist in the speedrun schema)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE speedrun.Run_Split CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE speedrun.Run CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE speedrun.Segment CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

CREATE TABLE speedrun.Segment (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id NUMBER NOT NULL,
    name        VARCHAR2(100) NOT NULL,
    ord         NUMBER NOT NULL
);

CREATE TABLE speedrun.Run (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL,
    category_id    NUMBER NOT NULL,
    platform_id    NUMBER NOT NULL,
    final_time_ms  NUMBER NOT NULL,
    video_link     VARCHAR2(255),
    submitted_at   DATE DEFAULT SYSDATE,
    status         VARCHAR2(20) DEFAULT 'pending',
    verified_by    NUMBER
);

CREATE TABLE speedrun.Run_Split (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         NUMBER NOT NULL REFERENCES speedrun.Run(id),
    segment_id     NUMBER NOT NULL REFERENCES speedrun.Segment(id),
    split_time_ms  NUMBER NOT NULL
);

-- 5. Insert Mock Data
INSERT INTO speedrun.Segment (category_id, name, ord) VALUES (1, 'Bob-omb Battlefield', 1);
INSERT INTO speedrun.Segment (category_id, name, ord) VALUES (1, 'Whomps Fortress', 2);
INSERT INTO speedrun.Segment (category_id, name, ord) VALUES (3, 'Start', 1);
INSERT INTO speedrun.Segment (category_id, name, ord) VALUES (3, 'End', 2);

-- Insert a "Verified PB" for User 2 (Category 1) and User 3 (Category 3)
-- This ensures that slower runs will be rejected during testing.
INSERT INTO speedrun.Run (user_id, category_id, platform_id, final_time_ms, video_link, status)
VALUES (2, 1, 3, 500000, 'https://youtube.com/watch?v=pb1', 'verified');

INSERT INTO speedrun.Run (user_id, category_id, platform_id, final_time_ms, video_link, status)
VALUES (3, 3, 1, 500000, 'https://youtube.com/watch?v=pb2', 'verified');

COMMIT;

-- 6. Create the Stored Procedure (Explicitly in speedrun schema)
CREATE OR REPLACE PROCEDURE speedrun.FinishRun(
    p_id_user      IN  NUMBER,
    p_id_category  IN  NUMBER,
    p_id_platform  IN  NUMBER,
    p_video_link   IN  VARCHAR2,
    p_splits_json  IN  VARCHAR2,
    p_id_run       OUT NUMBER,
    p_ret          OUT NUMBER
) AS
    v_expected    NUMBER;
    v_split_count NUMBER;
    v_final_time  NUMBER;
    v_pb          NUMBER;
BEGIN
    p_ret    := 0;
    p_id_run := NULL;

    -- Krok 2: Validace počtu mezičasů
    SELECT COUNT(*) INTO v_expected
    FROM speedrun.Segment
    WHERE category_id = p_id_category;

    SELECT COUNT(*) INTO v_split_count
    FROM JSON_TABLE(p_splits_json, '$[*]'
         COLUMNS (segment_id NUMBER PATH '$.segment_id' NULL ON ERROR));

    IF v_split_count != v_expected THEN
        ROLLBACK;
        RETURN;
    END IF;

    -- Krok 3: Výpočet celkového času
    SELECT SUM(split_time_ms) INTO v_final_time
    FROM JSON_TABLE(p_splits_json, '$[*]'
         COLUMNS (split_time_ms NUMBER PATH '$.split_time_ms' NULL ON ERROR));

    -- Krok PB: Validace osobního rekordu
    -- Hráč nemůže odeslat run s horším časem než je jeho nejlepší verifikovaný nebo čekající run (Anti-spam).
    SELECT MIN(final_time_ms) INTO v_pb
    FROM speedrun.Run
    WHERE user_id     = p_id_user
      AND category_id = p_id_category
      AND status      IN ('verified', 'pending');

    IF v_pb IS NOT NULL AND v_final_time >= v_pb THEN
        ROLLBACK;
        RETURN;
    END IF;

    -- Krok 4: INSERT Run
    INSERT INTO speedrun.Run
        (user_id, category_id, platform_id, final_time_ms,
         video_link, submitted_at, status, verified_by)
    VALUES
        (p_id_user, p_id_category, p_id_platform, v_final_time,
         p_video_link, SYSDATE, 'pending', NULL)
    RETURNING id INTO p_id_run;

    -- Krok 5: INSERT Run_Split
    INSERT INTO speedrun.Run_Split (run_id, segment_id, split_time_ms)
    SELECT p_id_run, jt.segment_id, jt.split_time_ms
    FROM JSON_TABLE(p_splits_json, '$[*]'
         COLUMNS (
             segment_id    NUMBER PATH '$.segment_id'    NULL ON ERROR,
             split_time_ms NUMBER PATH '$.split_time_ms' NULL ON ERROR
         )
    ) jt;

    COMMIT;
    p_ret := 1;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_ret    := 0;
        p_id_run := NULL;
END;
/
